export default {
  "01": require("../../assets/images/01.png"),
  "02": require("../../assets/images/02.png"),
  "03": require("../../assets/images/03.png"),
  "04": require("../../assets/images/04.png"),
  "05": require("../../assets/images/05.png"),
  "06": require("../../assets/images/06.png"),
  "07": require("../../assets/images/07.png"),
  "08": require("../../assets/images/08.png"),
  "09": require("../../assets/images/09.png"),
  "10": require("../../assets/images/10.png"),
  "11": require("../../assets/images/11.png"),
  "12": require("../../assets/images/12.png"),
  "13": require("../../assets/images/13.png"),
  "14": require("../../assets/images/14.png"),
  "15": require("../../assets/images/15.png"),
  "16": require("../../assets/images/16.png"),
  "17": require("../../assets/images/17.png"),
  "18": require("../../assets/images/18.png"),
  "19": require("../../assets/images/19.png"),
}
